apiVersion: v1
kind: Service
metadata:
  name: frosty-brown-9c050739d3-srv
  namespace: apps-release
spec:
  selector:
    app: frosty-brown-9c050739d3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7070
  type: ClusterIP